config/routes.rb
Rails.application.routes.draw do
  resources :patient_facility_insurances

  resources :clinic_facility_travellers

  resources :premises

  resources :payment_infos

  resources :addresses

  get 'profile/index'

  get 'profile/create'

  get 'profile/update'

  get 'profile/delete'

  get 'profile/show'

  get 'profile/read'

  resources :beauty_services

  resources :medicines

  resources :medical_tests

  devise_for :accounts,:controllers => {registrations: 'registrations',sessions: 'sessions'}
  devise_scope :account do
    get 'branch/sign_up' => 'registrations#new_branch' 
    post 'branch/sign_up' => 'registrations#create_branch'
    get 'centre/sign_up' => 'registrations#new_centre'
    post 'centre/sign_up' => 'registrations#create_centre'
    get  'branch/sign_in' => 'sessions#new_branch' 
    post 'branch/sign_in' => 'sessions#create_branch'
    get 'centre/sign_in' => 'sessions#new_centre' 
    post 'centre/sign_in' => 'sessions#create_centre'
  end

  root 'welcome#index'
  
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'welcome/demoindex' => 'welcome#demoindex'
  
  resources :welcome,:accounts,:properties,:patients,:staffs,:facilities,:profile
  
  get 'services/:id/index2' => 'services#index2',as: :branch_services
  get 'facility/:id/index2' => 'facilities#index2',as: :branch_facilities
  get 'services/book/:id' => 'services#book',as: :book_service
  get 'services/data_import' => 'services#data_import'
  get 'centres/data_import' => 'centres#data_import'
  resources :services do
    collection { post :import }
  end

  resources :centres do
    collection { post :import }
  end

  resources :centre_types do
    collection { post :import }
  end

  resources :staff_types do
    collection { post :import }
  end
  
  resources :facility_types do
    collection { post :import }
  end
  resources :service_types do
    collection { post :import }
  end

  resources :search do
    collection { get :index_app }
  end
  
  namespace :api, :path => "", :defaults => {:format => :json} do
    namespace :v1 do
      resources :search
      resources :registrations
    end
  end
  

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  
  belongs_to :centre
  belongs_to :staff_type
  
  validates :title, presence: true
  validates :first_name, presence: true,length: { minimum: 5 }
  validates :last_name, presence: true
  validates :gender, presence: true
  validates :centre, presence: true
  validates :gender, presence: true
  validates :staff_type, presence: true
  validates :degree, presence: true
  validates :qualification, presence: true
  validates :designation, presence: true
  validates :specialization, presence: true
  validates :language, presence: true
  validates :email, presence: true
  validates :mobile, presence: true
  validates :address_line1, presence: true
  validates :pincode, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
end

app/models/staff_type.rb
class StaffType < ActiveRecord::Base
  
  has_many :staffs
  
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  #load_and_authorize_resource param_method: :staff_params
  
  def new
    if current_account.has_role? 'property'
      @property = current_account.property
    elsif current_account.has_role? 'centre'
      @property = current_account.centre.property
    end
    @staff = @property.staffs.new
  end
  
  def create
    if current_account.has_role? 'property'
      @property = current_account.property
    elsif current_account.has_role? 'centre'
      @property = current_account.centre.property
    end
    @staff = @property.staffs.new(staff_params)
    if @staff.save
      redirect_to @staff
    else
      render('new')
    end
  end
  
  def index2
    @property = current_account.property
    @staffs = @property.staffs
  end
  
  def index
    if current_account.has_role? 'branch_admin'
      @property = current_account.property
      @staffs = @property.staffs.order(:centre)
    elsif current_account.has_role? 'branch'
      @property = current_account.centre.property
      @staffs = @property.staffs.where(centre: current_account.centre.name).order(:centre)
    end
  end
  
  def show
    @property = current_account.property
    @staff = Staff.find(params[:id])
  end
  
  def edit
    @property = current_account.property
    @staff = Staff.find(params[:id])
  end
  
  def update
    @property = current_account.property
    @staff = Staff.find(params[:id])
    if @staff.update(staff_params)
      redirect_to @staff
    else
      render('edit')
    end
  end
  
  def delete
    
  end
  
  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy
    redirect_to staffs_path
  end
  
  private
  def staff_params
    params.require(:staff).permit(:property_id,:staff_type_id,:centre,:staff_id,:title,:first_name,:last_name,:gender,:email,:country_mobile_code,:mobile,:designation,:biography,:qualification,:degree,:specialization,:language,:address_line1,:pincode,:city,:state,:country)
  end
  
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= link_to '<<Back', :back,:class => 'btn btn-primary' %>
<div class="container text-primary">
  <div class="row">
    <div class="panel panel-success col-lg-6 col-lg-offset-3">
      <div class="panel-heading">
        Staff
      </div>
      <div class="panel-body">
	<% if @staff.errors.any? %>
	  	<div id="error_explanation">
	    	<h2><%= pluralize(@staff.errors.count, "error") %> prohibited from being saved:</h2>
	    	<ul>
	    		<% @staff.errors.full_messages.each do |msg| %>
	      			<li><%= msg %></li>
	    		<% end %>
	    	</ul>
	  	</div>
  	<% end %>

		<%= form_for @staff do |f| %>
                  <em class="label label-danger">fields marked with (*) are cumpulsory</em>
					<h3>Profile Details</h3></br>

                  <div class="form-group ">
                    <%= f.label :title, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.select :title,options_for_select([['Mr.','Mr.'],['Ms.','Ms.']], class: 'form-control') %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :first_name,'Name of Clinic', :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.text_field :first_name, :autofocus => true, placeholder: 'First Name', class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :last_name,'Name of Clinic', :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.text_field :last_name, :autofocus => true, placeholder: 'Last Name', class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :gender,'Name of Clinic', :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.label :male %>
                      <%= f.radio_button :gender,"Male" %>
                      <%= f.label :female %>
                      <%= f.radio_button :gender,"Female" %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :branch,'Name of Clinic', :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <% if current_account.has_role? 'centre' %>
                          <%= f.text_field :centre, value: current_account.centre.name, disabled: true , class: 'form-control'%>
                      <% else %>
                          <%= f.collection_select :centre, @property.centres.order(:name),:name,:name, :prompt=> "Select", class: 'form-control' %><br>
                      <% end %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :staff_type,'Name of Clinic', :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :staff_type_id, StaffType.order(:name),:id,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :working_hours, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.time_select :start_time,ampm: true, class: 'form-control' %>to
                      <%= f.time_select :end_time,ampm: true, class: 'form-control' %>
                     </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :degree, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :degree, MessageType.find_by_name('Degree').messages.order(:name),:id,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :qualification, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :qualification, MessageType.find_by_name('Qualification').messages.order(:name),:id,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :specialization, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :specialization, MessageType.find_by_name('Specialization').messages.order(:name),:id,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :designation, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :designation, MessageType.find_by_name('Designation').messages.order(:name),:id,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :language, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :language, Language.order(:name),:id,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :biography, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.text_area :biography, class: 'form-control' %>
                    </div>
                  </div>

			

                  <div class="form-group ">
                    <%= f.label :email, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.email_field :email, class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :mobile, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :country_mobile_code, Country.order(:name),:mobile_code,:mobile_code , :prompt=> "Select"%>
                      <%= f.telephone_field :mobile, class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :address_line1, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.text_field :address_line1, class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :address_line2, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.text_field :address_line2, class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :address_line3, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.text_field :address_line3, class: 'form-control' %>
                    </div>
                  </div>
                <div class="form-inline">
                  <div class="form-group ">
                    <%= f.label :pincode, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :pincode, Postalcode.order(:name),:name,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :city, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :city, City.order(:name),:name,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :state, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :state, State.order(:name),:name,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                  <div class="form-group ">
                    <%= f.label :country, :class=> 'required' %>
                    <div class="input-group">
      <span class="input-group-addon ">
          <i class="glyphicon glyphicon-plus"></i></span>
                      <%= f.collection_select :country, Country.order(:name),:name,:name, :prompt=> "Select", class: 'form-control' %>
                    </div>
                  </div>

                </div>
                  <div class="panel-footer">
                    <div class="input-group ">

                      <%= f.submit :class => 'btn btn-primary' %>

                    </div>

        </div>

		<% end %>
	</div>
</div>
</div>
    </div>

app/views/staffs/_form_contact_details.html.erb
<h2>New Staff</h2>
<%= form_for @staff do |f| %>

	<% if @staff.errors.any? %>
  	<div id="error_explanation">
    	<h2><%= pluralize(@staff.errors.count, "error") %> prohibited from being saved:</h2>
    	<ul>
    		<% @staff.errors.full_messages.each do |msg| %>
      			<li><%= msg %></li>
    		<% end %>
    	</ul>
  	</div>
  	<% end %>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :mobile %><br>
    <%= f.collection_select :country_mobile_code, CountryMobileCode.order(:name),:id,:name %>
    <%= f.telephone_field :mobile %>
  </p>

  <p>
    <%= f.label :pincode %><br>
    <%= f.text_field :pincode %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.collection_select :city, City.order(:name),:id,:name, default: "Select" %>
  </p>
  
  <p>
    <%= f.label :state %><br>
    <%= f.collection_select :state, State.order(:name),:id,:name, default: "Select" %>
  </p>
  
  <p>
    <%= f.label :country %><br>
    <%= f.collection_select :country, Country.order(:name),:id,:name, default: "Select" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/staffs/_form_personal_details.html.erb
<h2>Personal Details</h2>
<%= form_for @staff do |f| %>

	<% if @staff.errors.any? %>
  	<div id="error_explanation">
    	<h2><%= pluralize(@staff.errors.count, "error") %> prohibited from being saved:</h2>
    	<ul>
    		<% @staff.errors.full_messages.each do |msg| %>
      			<li><%= msg %></li>
    		<% end %>
    	</ul>
  	</div>
  	<% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.select :title,options_for_select([['Mr.','Mr.'],['Ms.','Ms.']]) %>
  </p>

  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
 
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>
  
  <p>
    <%= f.label :gender %>
    <%= f.label :male %>
    <%= f.radio_button :gender,"Male" %>
    <%= f.label :female %>
    <%= f.radio_button :gender,"Male" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/staffs/edit.html.erb
<%= render('staffs/form') %>
<%= link_to 'Back', staffs_path %>

app/views/staffs/edit_contact_details.html.erb
<%= render('staffs/form_contact_details') %>
<%= link_to 'Back', staffs_path %>

app/views/staffs/edit_personal_details.html.erb
<%= render('staffs/form_personal_details') %>
<%= link_to 'Back', staffs_path %>

app/views/staffs/edit_work_details.html.erb
<%= render('staffs/form_work_details') %>
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<div class="row" style="color:#ff0000 ; background:#cccccc ; padding:20px; margin:0px;"%>
	<div class="col-md-4 offset2">
	</div>
	<% if can? :create, Staff %>
		<%= link_to "Add Staff", new_staff_path %>
	<% end %>
	<h3>Staffs</h3>
	<% @staffs.split(:centre).each do |staffs|%><%= staffs %>
	<% if staffs.first %>
		<strong><%= link_to  staffs.first.centre , centre_path(Centre.find_by_name(staffs.first.centre)) %></strong><br>
	<% end %>
	<div class="col-md-8 offset2">
		<% staffs.each do |staff| %>
			<div class="row" style="color:#ff0000 ; background:#77ddff ; padding:20px; margin:0px;" %>
				<table>
					  <strong>Nmae</strong>
					  <%= link_to (staff.title + staff.first_name + staff.last_name) , staff_path(staff) %><br>
					  <strong>Staff Type</strong><%= staff.staff_type.name %><br>
					  <strong>Mobile</strong><%= staff.mobile %><br>
					  
					<%= link_to "Edit", edit_staff_path(staff) %>
					<%= link_to 'Delete', staff_path(staff), method: :delete,data: { confirm: 'Are you sure?'}%></td>
					
					</table>
				</div><hr>
			<% end %>
		</div>
	<% end %>
</div>

app/views/staffs/index2.html.erb
<div class="row" style="color:#ff0000 ; background:#cccccc ; padding:20px; margin:0px;"%>
	<div class="col-md-4 offset2">
	</div>
	<% if can? :create, Staff %>
		<%= link_to "Add Staff", new_staff_path %>
	<% end %>
	<h3>Staffs</h3>
	<div class="col-md-8 offset2">
		<% @staffs.each do |staff| %>
			<div class="row" style="color:#ff0000 ; background:#77ddff ; padding:20px; margin:0px;" %>
				<table>
					  <strong>Nmae</strong>
					  <%= link_to (staff.title + staff.first_name + staff.last_name) , staff_path(staff) %><br>
					  
					  <strong>Staff Type</strong><%= staff.centre %><br>
					  <strong>Mobile</strong><%= staff.mobile %><br>
					  
					<%= link_to "Edit", edit_staff_path(staff) %>
					<%= link_to 'Delete', staff_path(staff), method: :delete,data: { confirm: 'Are you sure?'}%></td>
					
					</table>
				</div><hr>
			<% end %>
		</div>
	</div>

app/views/staffs/new.html.erb
<%= render('staffs/form') %>

app/views/staffs/show.html.erb
<%= link_to 'Back', staffs_path %>
<div class="row" style="color:#ff0000 ; background:#cccccc ; padding:50px; margin:0px;" %>
	<div class="col-md-1 offset2">
	</div>
	<h3> Details</h3></br>
	<div class="col-md-4 offset2">
		<div class="row" style="color:#ff0000 ; background:#8899cc ; padding:20px; margin:0px;" %>
			<table>
				<h3>Profile</h3></br>
				  <strong>Name:</strong>
				  <%= @staff.title %>
				  <%= @staff.first_name %>
				  <%= @staff.last_name %><br>
				
				  <strong>Gender:</strong>
				  <%= @staff.gender %><br>
				  
				  <strong>Branch:</strong>
				  <%= @staff.centre %><br>
				  
				  <strong>Staff Type:</strong>
				  <%= @staff.staff_type.name %><br>
				  
				  <strong>Working Hours:</strong>
				  <%= @staff.start_time %>to 
				  <%= @staff.end_time %><br>
				  
				  <strong>Degree:</strong>
				  <%= @staff.degree %><br>
				  
				  <strong>Qualification:</strong>
				  <%= @staff.qualification %><br>
				  
				  <strong>Specialization:</strong>
				  <%= @staff.specialization %><br>
				  
				  <strong>Designation:</strong>
				  <%= @staff.designation %><br>
				  
				  <strong>Language:</strong>
				  <%= @staff.language %><br>
				  
				  <strong>Biography:</strong>
				  <%= @staff.biography %><br>
			</table>
		</div>
		
		<div class="row" style="color:#ff0000 ; background:#889955 ; padding:20px; margin:0px;" %>
			<table>
				<h3>Location Details</h3></br>
				
				<strong>Email:</strong>
			  	<%= @staff.email %><br>
			  	
				  <strong>Mobile:</strong>
				  <%= @staff.country_mobile_code %>
				  <%= @staff.mobile %><br>
				
				<p>
				  <strong>Address:</strong>
				  <%= @staff.address_line1 %>
				  <%= @staff.address_line2 %>
				  <%= @staff.address_line3 %>
				</p>
				
				<p>
				  <strong>Pincode:</strong>
				  <%= @staff.pincode %>
				</p>
				
				<p>
				  <strong>City:</strong>
				  <%= @staff.city %>
				</p>
				
				<p>
				  <strong>State:</strong>
				  <%= @staff.state %>
				</p>
				
				<p>
				  <strong>Country:</strong>
				  <%= @staff.country %>
				</p>
			</table>
		</div>
		<%= link_to "Edit", edit_staff_path(@staff) %>
		<%= link_to 'Delete', staff_path(@staff),method: :delete,data: { confirm: 'Are you sure?'}%>
	</div>
</div>

app/views/staffs/show_contact_details.html.erb
<p>
  <strong>First Name:</strong>
  <%= @staff.first_name %>
</p>
 
<p>
  <strong>Last Name:</strong>
  <%= @staff.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @staff.gender %>
</p>


<%= link_to 'Back', patients_path %>
<%= link_to "Edit", edit_patient_path(@staff) %>
<%= link_to 'Delete', patient_path(@staff),method: :delete,data: { confirm: 'Are you sure?'}%>

app/views/staffs/show_personal_details.html.erb
<p>
  <strong>First Name:</strong>
  <%= @staff.first_name %>
</p>
 
<p>
  <strong>Last Name:</strong>
  <%= @staff.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @staff.gender %>
</p>



<%= link_to 'Back', patients_path %>
<%= link_to "Edit", edit_patient_path(@staff) %>
<%= link_to 'Delete', patient_path(@staff),method: :delete,data: { confirm: 'Are you sure?'}%>

app/views/staffs/show_work_details.html.erb
<p>
  <strong>First Name:</strong>
  <%= @staff.first_name %>
</p>
 
<p>
  <strong>Last Name:</strong>
  <%= @staff.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @staff.gender %>
</p>


<%= link_to 'Back', patients_path %>
<%= link_to "Edit", edit_patient_path(@staff) %>
<%= link_to 'Delete', patient_path(@staff),method: :delete,data: { confirm: 'Are you sure?'}%>