config/routes.rb
Rails.application.routes.draw do
  resources :patient_facility_insurances

  resources :clinic_facility_travellers

  resources :premises

  resources :payment_infos

  resources :addresses

  get 'profile/index'

  get 'profile/create'

  get 'profile/update'

  get 'profile/delete'

  get 'profile/show'

  get 'profile/read'

  resources :beauty_services

  resources :medicines

  resources :medical_tests

  devise_for :accounts,:controllers => {registrations: 'registrations',sessions: 'sessions'}
  devise_scope :account do
    get 'branch/sign_up' => 'registrations#new_branch' 
    post 'branch/sign_up' => 'registrations#create_branch'
    get 'centre/sign_up' => 'registrations#new_centre'
    post 'centre/sign_up' => 'registrations#create_centre'
    get  'branch/sign_in' => 'sessions#new_branch' 
    post 'branch/sign_in' => 'sessions#create_branch'
    get 'centre/sign_in' => 'sessions#new_centre' 
    post 'centre/sign_in' => 'sessions#create_centre'
  end

  root 'welcome#index'
  
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'welcome/demoindex' => 'welcome#demoindex'
  
  resources :welcome,:accounts,:properties,:patients,:staffs,:facilities,:profile
  
  get 'services/:id/index2' => 'services#index2',as: :branch_services
  get 'facility/:id/index2' => 'facilities#index2',as: :branch_facilities
  get 'services/book/:id' => 'services#book',as: :book_service
  get 'services/data_import' => 'services#data_import'
  get 'centres/data_import' => 'centres#data_import'
  resources :services do
    collection { post :import }
  end

  resources :centres do
    collection { post :import }
  end

  resources :centre_types do
    collection { post :import }
  end

  resources :staff_types do
    collection { post :import }
  end
  
  resources :facility_types do
    collection { post :import }
  end
  resources :service_types do
    collection { post :import }
  end

  resources :search do
    collection { get :index_app }
  end
  
  namespace :api, :path => "", :defaults => {:format => :json} do
    namespace :v1 do
      resources :search
      resources :registrations
    end
  end
  

end

app/controllers/staff_types_controller.rb
class StaffTypesController < ApplicationController
  
  #load_and_authorize_resource param_method: :staff_type_params
  
  def new
    @staff_type = StaffType.new
  end
  
  def create
    @staff_type = StaffType.new(staff_type_params)
    if @staff_type.save
      redirect_to @staff_type
    else
      render('new')
    end
  end
  
  def index
    @staff_types = StaffType.all
  end
  
  def show
    @staff_type = StaffType.find(params[:id])
  end
  
  def edit
    @staff_type = StaffType.find(params[:id])
  end
  
  def update
    @staff_type = StaffType.find(params[:id])
    if @staff_type.update(staff_type_params)
      redirect_to @staff_type
    else
      render('edit')
    end
  end
  
  def delete
    
  end
  
  def destroy
    @staff_type = StaffType.find(params[:id])
    @staff_type.destroy
    redirect_to staff_types_path
  end
  
  def import
    if params[:file]
      StaffType.import(params[:file])
      redirect_to staff_types_path, notice: "Centre Types imported."
    else
      render('new')
    end
  end
  
  private
  def staff_type_params
    params.require(:staff_type).permit(:name,:description)
  end
  
end

app/helpers/staff_types_helper.rb
module StaffTypesHelper
end

app/views/staff_types/_form.html.erb
<%= form_for @staff_type do |f| %>

	<% if @staff_type.errors.any? %>
  	<div id="error_explanation">
    	<h2><%= pluralize(@staff_type.errors.count, "error") %> prohibited from being saved:</h2>
    	<ul>
    		<% @staff_type.errors.full_messages.each do |msg| %>
      			<li><%= msg %></li>
    		<% end %>
    	</ul>
  	</div>
  	<% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/staff_types/edit.html.erb

<%= render('staff_types/form')%>
<%= link_to 'Back', staff_types_path %>

app/views/staff_types/index.html.erb
<%= link_to "Add Staff Type", new_staff_type_path %>
<h1>Listing Staff Types</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>
 
  <% @staff_types.each do |staff_type| %>
    <tr>
      <td><%= staff_type.name %></td>
      <td><%= staff_type.description %></td>
      <td><%= link_to "Show", staff_type_path(staff_type) %>
    	  <%= link_to "Edit", edit_staff_type_path(staff_type) %>
    	  <%= link_to 'Delete', staff_type_path(staff_type), method: :delete,data: { confirm: 'Are you sure?'}%></td>
    </tr>
  
  <% end %>
</table>

app/views/staff_types/new.html.erb


<%= render('staff_types/form')%>
<%= link_to 'Back', staff_types_path %>

<%= form_tag import_facility_types_path, enforce_utf8: true ,miultipart: true do |f| %>
	<%= file_field_tag :file %>
	<%= submit_tag "Import"%>
<% end %>

app/views/staff_types/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @staff_type.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @staff_type.description %>
</p>
<%= link_to 'Back', staff_types_path %>
<%= link_to "Edit", edit_staff_type_path(@staff_type) %>
<%= link_to 'Delete', staff_type_path(@staff_type),method: :delete,data: { confirm: 'Are you sure?'}%>