config/routes.rb
Rails.application.routes.draw do
  resources :patient_facility_insurances

  resources :clinic_facility_travellers

  resources :premises

  resources :payment_infos

  resources :addresses

  get 'profile/index'

  get 'profile/create'

  get 'profile/update'

  get 'profile/delete'

  get 'profile/show'

  get 'profile/read'

  resources :beauty_services

  resources :medicines

  resources :medical_tests

  devise_for :accounts,:controllers => {registrations: 'registrations',sessions: 'sessions'}
  devise_scope :account do
    get 'branch/sign_up' => 'registrations#new_branch' 
    post 'branch/sign_up' => 'registrations#create_branch'
    get 'centre/sign_up' => 'registrations#new_centre'
    post 'centre/sign_up' => 'registrations#create_centre'
    get  'branch/sign_in' => 'sessions#new_branch' 
    post 'branch/sign_in' => 'sessions#create_branch'
    get 'centre/sign_in' => 'sessions#new_centre' 
    post 'centre/sign_in' => 'sessions#create_centre'
  end

  root 'welcome#index'
  
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'welcome/demoindex' => 'welcome#demoindex'
  
  resources :welcome,:accounts,:properties,:patients,:staffs,:facilities,:profile
  
  get 'services/:id/index2' => 'services#index2',as: :branch_services
  get 'facility/:id/index2' => 'facilities#index2',as: :branch_facilities
  get 'services/book/:id' => 'services#book',as: :book_service
  get 'services/data_import' => 'services#data_import'
  get 'centres/data_import' => 'centres#data_import'
  resources :services do
    collection { post :import }
  end

  resources :centres do
    collection { post :import }
  end

  resources :centre_types do
    collection { post :import }
  end

  resources :staff_types do
    collection { post :import }
  end
  
  resources :facility_types do
    collection { post :import }
  end
  resources :service_types do
    collection { post :import }
  end

  resources :search do
    collection { get :index_app }
  end
  
  namespace :api, :path => "", :defaults => {:format => :json} do
    namespace :v1 do
      resources :search
      resources :registrations
    end
  end
  

end

app/models/centre.rb
class Centre < ActiveRecord::Base
  belongs_to :centre_type
  #belongs_to :property
  belongs_to :account
  has_many :centres
  has_many :staffs
  has_many :services
  has_many :facilities
  geocoded_by :full_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  def self.sort_by_price(serviceable_type, serviceable_id)
    order(services.where(serviceable_type: 'MedicalTest', serviceable_id: 2).map {|s| getPayablePrice(s)}.sum)
  end
  default_scope {order('distance ASC')}

  #reverse_geocoded_by :latitude, :longitude
  #after_validation :reverse_geocode  # auto-fetch address
  #has_attached_file :avatar,:styles => {:medium => "300x300",:thumb => "100x100"},:default_url => "/images/centre/missing.png"
  
  #validates :attachment, presence: true , content_type:  {:content_type => "image/jpeg"},size: {:in => 0..10.kilobytes}
  
  #validates_attachment_file_name :avatar, :matches => [/png\Z/ ,/jpeg\Z/]
  
  validates :name, presence: true,length: { minimum: 5 }

  default_scope { order('distance ASC') }


  def self.import(file, centre_id, centre_type_id)
    allowed_attributes = ['name','company','website','centre_type_id','centre_id','secondary_email',
                          'close_day','open_time','close_time','lunch_start_time','lunch_end_time','employee_count','currency',
                          'minimum_consultancy_fee','address_line1','address_line2','address_line3',
                          'landmark1','landmark2','landmark3','country_mobile_code','secondary_mobile',
                          'country_mobile_code','pincode','city','state','country']

    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      centre = Centre.new
      row['open_time'] = Time.parse(row['open_time']).to_datetime if row['open_time']
      row['close_time'] = Time.parse(row['close_time']).to_datetime if row['close_time']
      row['lunch_start_time'] = Time.parse(row['lunch_start_time']).to_datetime if row['lunch_start_time']
      row['lunch_end_time'] = Time.parse(row['lunch_end_time']).to_datetime if row['lunch_end_time']
      centre.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
      centre.centre_id = centre_id if centre_id
      centre.centre_type_id = centre_type_id
      centre.account_id = 0
      centre.save!
      centre.centre_id = centre.id
      centre.save
    end
  end



  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def full_address
    [address_line1, address_line2, address_line3, city, pincode, state, country].compact.join(', ')
  end
end

app/models/centre_type.rb
class CentreType < ActiveRecord::Base
  
  has_many :centres
  has_many :services
  validates :name, presence: true,length: { minimum: 5 }
  #attributes_accessible :name,:description
  
  def self.import(file)
    spreadsheet = open_spreadsheet(file)# || Roo::Excelx.new('./public/centre_types.xlsx')
    #spreadsheet = Roo::Spreadsheet.open(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      centre_type = find_by_id(row["id"]) || new
      centre_type.attributes = row.to_hash#.slice(attr_accessible)
      centre_type.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file)
      when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.name}"
    end
  end
  
end

app/controllers/centres_controller.rb
class CentresController < ApplicationController
  load_and_authorize_resource param_method: :centre_params
  
  def new
    @account = Account.new
    @account.build_centre
    #@centre = Centre.new
  end
  
  def create
    if @account.save
      redirect_to centres_path
    else
      render('new')
    end
  end
  
  def index
    if current_account.has_role? 'branch_admin'
      @centres = current_account.centre.centres
    elsif current_account.has_role? 'branch'
      @centres = [current_account.centre]
    end
  end
  
  def show
    @centre = Centre.find(params[:id])
  end
  
  def edit
    @centre = Centre.find(params[:id])
  end
  
  def update
    @centre = Centre.find(params[:id])
    if @centre.update(centre_params)
      redirect_to @centre
    else
      render('edit')
    end
  end
  
  def delete
    
  end
  
  def destroy
    @centre = Centre.find(params[:id])
    @centre.account.destroy
    @centre.destroy
    redirect_to centres_path
  end

  def data_import

  end

  def import
    if params[:file]
      if params[:centre]
        centre_id = params[:centre][:id]
      else
        centre_id = nil
      end
      filename = File.basename(params[:file].original_filename, ".*" )
      if(params[:centre_type])
        centre_type_id = params[:centre_type][:id]
      else
        centre_type = CentreType.find_by_name(:name => filename.humanize)
        if not centre_type
          centre_type = CentreType.new(:name => filename.humanize)
          centre_type.save
          centre_type_id = centre_type.id
        end
      end
      Centre.import(params[:file], centre_id, centre_type_id)
      flash[:notice]= "Centres imported."
      redirect_to :back
    else
      render('new')
    end
  end

  private
  def centre_params
    params.require(:centre).permit(:name,:centre_type_id,:centre_id,:name,:secondary_email,:close_day,:open_time,:close_time,:lunch_start_time,:lunch_end_time,:address_line1,:address_line2,:landmark,:country_mobile_code,:mobile,:pincode,:city,:state,:country )
  end
  
end

app/helpers/centres_helper.rb
module CentresHelper
  def address(centre)
      address = ''
      address = address + centre.address_line1 if centre.address_line1
      address = address + centre.address_line2 if centre.address_line2
      address = address + centre.address_line3 if centre.address_line3
      address = address + centre.landmark1 if centre.landmark1
      address = address + centre.pincode if centre.pincode
      address = address + centre.city if centre.city
      return address
  end

  def price(lab, test_ids, test_type)
    services = Service.where(centre_id: lab.id, serviceable_id: test_ids, serviceable_type: test_type)
    total_price = 0.0
    total_discount = 0.0
    services.each do |service|
      if service.price
        total_price = total_price + service.price
      end
      if service.dd_price
        total_discount = total_discount + service.dd_price
      end
    end
    return [total_price, (total_discount/total_price)*100,total_discount]
  end
end

app/views/centres/_form.html.erb
<div class="row" style="color:#ff0000 ; background:#cccccc ; padding:50px; margin:0px;" %>
	<div class="col-md-1 offset2">
	</div>
	<h2>Edit Branch Details</h2>

	<% if @centre.errors.any? %>
  	<div id="error_explanation">
    	<h2><%= pluralize(@centre.errors.count, "error") %> prohibited from being saved:</h2>
    	<ul>
    		<% @centre.errors.full_messages.each do |msg| %>
      			<li><%= msg %></li>
    		<% end %>
    	</ul>
  	</div>
  	<% end %>
  	
  	<div class="col-md-6 offset2">
		<%= form_for @centre do |f| %>
			<div class="row" style="color:#ff0000 ; background:#8899cc ; padding:20px; margin:0px;" %>
				<table>
					<h3>Profile Details</h3></br>

					  <p>
					    <%= f.label :name %><br>
					    <%= f.text_field :name %>
					  </p>
					 
					  <p>
					  	<%= f.label :centre_type %></br>
						<%= f.collection_select :centre_type_id, CentreType.order(:name),:id,:name, default: "Select" %>
					  </p>
					  
					  <p>
					    <%= f.label :company %><br>
					    <%= f.text_field :company %>
					  </p>
					  
					  <p>
					    <%= f.label :website %><br>
					    <%= f.url_field :website %>
					  </p>
					  
					  <p>
					    <%= f.label :employee_count %><br>
					    <%= f.collection_select :employee_count, MessageType.find_by_name('Employee_count').messages.order(:name),:name,:name , :prompt=> "Select"%>
					  </p>
					 
					  <p>
					  	<%= f.label :minimum_consultancy_fee %></br>
					  	<%= f.collection_select :currency, Country.order(:name),:currency,:currency , :prompt=> "Select"%>
					    <%= f.text_field :minimum_consultancy_fee %>
					  </p>
					  
					  <p>
					    <%= f.label :close_day %><br>
					    <%= f.select :close_day, options_for_select([['Sunday','Sunday'],['Monday','Monday'],['Tuesday','Tuesday'],['Wednesday','Wednesday'],['Thursday','Thursday'],['Friday','Friday'],['Saturday','Saturday']]) %>
					  </p>
					  
					  <p>
					    <%= f.label :clinic_timing %><br>
					    <%= f.time_select :open_time, ampm: true%> to <%= f.time_select :close_time, ampm: true %>
					  </p>
					  
					  <p>
					    <%= f.label :lunch_time %><br>
					    <%= f.time_select :lunch_start_time , ampm: true%> to <%= f.time_select :lunch_end_time, ampm: true %>
					  </p>
					  
				</table>
			</div>

			<div class="row" style="color:#ff0000 ; background:#889955 ; padding:20px; margin:0px;" %>
				<table>
					<h3>Location Details</h3></br>

					  <p>
					    <%= f.label :secondary_email %><br>
					    <%= f.email_field :secondary_email %>
					  </p>
					  
					  	<%= f.label :mobile,'Secondary Mobile' %></br>
		    			<%= f.collection_select :country_mobile_code, Country.order(:name),:mobile_code,:mobile_code , :prompt=> "Select"%>
		    			<%= f.telephone_field :secondary_mobile %></br>
					
					  <p>
					    <%= f.label :address_line1 %><br>
					    <%= f.text_field :address_line1 %>
					  </p>
					 
					 <p>
					    <%= f.label :address_line2 %><br>
					    <%= f.text_field :address_line2 %>
					  </p>
					  
					  <p>
					    <%= f.label :address_line3 %><br>
					    <%= f.text_field :address_line3 %>
					  </p>
					  
					  <p>
					    <%= f.label :landmark1 %><br>
					    <%= f.text_field :landmark1 %>
					  </p>
					  
					  <p>
					    <%= f.label :landmark2 %><br>
					    <%= f.text_field :landmark2 %>
					  </p>
					  
					  <p>
					    <%= f.label :landmark3 %><br>
					    <%= f.text_field :landmark3 %>
					  </p>
					  
					  <p>
					    <%= f.label :pincode %>
					    <%= f.collection_select :pincode, Postalcode.order(:name),:name,:name, :prompt=> "Select" %>
					
					    <%= f.label :city %>
					    <%= f.collection_select :city, City.order(:name),:name,:name, :prompt=> "Select" %>
					  
					    <%= f.label :state %>
					    <%= f.collection_select :state, State.order(:name),:name,:name, :prompt=> "Select"%>
					 
					    <%= f.label :country %>
					    <%= f.collection_select :country, Country.order(:name),:name,:name, :prompt=> "Select"%>
					  </p>
				</table>
			</div>
			<p>
		    <%= f.submit %>
		  </p>
		<% end %>
	</div>
</div>


app/views/centres/data_import.html.erb
<section class="container" xmlns="http://www.w3.org/1999/html">
  <section class="row">

    <div class="col-sm-6 col-sm-offset-3" >
      <div class="panel panel-default">
        <header class="panel-heading font-bold">
          Import Centre list through Excel
        </header>

        <div class="panel-body">


          <%= form_tag import_centres_path, multipart: true do %>


              <%if current_account.has_role? :admin%>
                  <div class="form-group">
                    <%= label_tag(:centre, "Centre", :class => 'col-sm-3 control-label') %>
                    <div class="col-sm-7">
                      <%= collection_select(:centre, :id, Centre.all,:id,:name, options ={:prompt => "Select a Centre"},{:id => 'centre_select'})%>
                    </div>

                  </div>
              <% elsif current_account.has_role? :branch_admin %>
                  <div class="form-group">
                    <%= label_tag(:centre, "Centre", :class => 'col-sm-3 control-label') %>
                    <div class="col-sm-7">
                      <%= collection_select(:centre, :id, current_account.centre.centres,:id,:name, options ={:prompt => "Select a Centre"},{:id => 'centre_select'})%>
                    </div>

                  </div>
              <%end%>
              <div class="form-group">
                <%= label_tag(:centre_type, "Centre", :class => 'col-sm-3 control-label') %>
                <div class="col-sm-7">
                  <%= collection_select(:centre_type, :id, CentreType.all,:id,:name, options ={:prompt => "Select a Centre Type"},{:id => 'centre_type_select'})%>
                </div>

              </div>

              <div class="form-group">
                <%= label_tag :file, "Browse Excel File", :class => 'col-sm-3 control-label' %>
                <div class="col-sm-6">
                  <%= file_field_tag :file, :class => 'form-control' %>
                </div>
              </div>

              <div class="line line-dashed line-lg pull-in"></div>

              <div class="form-actions center-block">
                <%= submit_tag "Import", :class => "btn btn-primary" %>
              </div>

          <% end %>

        </div>
        <p align="right"><% link_to("Download Excel Template", "https://dl-web.dropbox.com/get/CampusMitra-%20Batch_data_import.xlsx?_subject_uid=63340203&w=AADcycPbMAq-EUTtQrGApBurcpQd2CaBs9U0fkUGAhm_cA&dl=1",:class=>"btn btn-primary") %> </p>
        <br/><br />
      </div>
    </div>

  </section>
</section>

app/views/centres/edit.html.erb
<%= link_to '<<Back', centres_path %>
<%= render('centres/form') %>

app/views/centres/index.html.erb
<div class="row" style="color:#ff0000 ; background:#cccccc ; padding:20px; margin:0px;"%>
	<div class="col-md-4 offset2">
	</div>
	<% if can? :create, Centre %>
		<%= link_to "Add Branch", branch_sign_up_path %>
	<% end %>
	<%= form_tag import_services_path, enforce_utf8: true ,miultipart: true do |f| %>
		<%= label_tag :file,'Add Services'%>
		<%= file_field_tag :file %>
		<%= submit_tag "Import"%>
	<% end %>
	<h3>Branches</h3>
	<div class="col-md-8 offset2">
		<% @centres.each do |centre| %>
			<div class="row" style="color:#ff0000 ; background:#77ddff ; padding:20px; margin:0px;" %>
				<table>
					<strong>Name:</strong>
					<% if can? :show, Centre %>
						<%= link_to centre.name , centre_path(centre) %>
					<% end %><br>
					<strong>Centre Type:</strong><%= centre.centre_type.name %><br>
			      	<strong>Email:</strong><%= centre.account.email %><br>
			      	<strong>Mobile: </strong><%= centre.account.mobile %><br>
			      	
			      	<% if can? :show, Service %>
			    	  	<%= link_to "Services", branch_services_path(centre) %>
			    	<% end %>
			    	<% if can? :show, Facility %>
			    	  	<%= link_to 'Facilities', branch_facilities_path(centre)%>
			    	<% end %><br>
			      	<% if can? :edit, Centre  %>
			    	  	<%= link_to "Edit", edit_centre_path(centre) %>
			    	<% end %>
			    	<% if can? :destroy, Centre %>
			    	  	<%= link_to 'Delete', centre_path(centre), method: :delete,data: { confirm: 'Are you sure?'}%>
			    	<% end %>
				</table>
			</div><hr>
		<% end %>
	</div>
</div>
  

app/views/centres/new.html.erb
<div class="row" style="color:#ff0000 ; background:#aacccc ; padding:50px; margin:0px;" %>
	<%= link_to '<<Back', :back %>
	<div class="col-md-1 offset2">
	</div>
	<h2>Add Branch</h2>
	<%= devise_error_messages! %>
		<div class="col-md-4 offset2">
			<%= form_for @account,url: centres_path  do |f| %>
			<div class="row" style="color:#ff0000 ; background:#8899cc ; padding:20px; margin:0px;" %>
					<table>
						<em>fields marked with (*) are cumpulsory</em>
						<h3>Profile Details</h3></br>
				    	<%= f.fields_for :centre do |p| %>
				    		
				    		<%= p.text_field :centre_id,value: current_account.centre.id,disabled: true %><br>
					      
					        <%= p.label :name,'Name of Clinic', class: 'required' %></br>
					        <%= p.text_field :name %><br>
					        
						  	<%= p.label :centre_type %></br>
							<%= p.collection_select :centre_type_id, CentreType.order(:name),:id,:name, default: "Select" %><br>   
					          	
					    <% end %>	      
					</table>
				</div>
			
			
				<div class="row" style="color:#ff0000 ; background:#77ddff ; padding:20px; margin:0px;" %>
					<table>
						<em>fields marked with (*) are cumpulsory</em>
						<h3>Login Details</h3></br>	
						  <div class="field">
						    <%= f.label :mobile, class: 'required' %><br />
						    <%= f.telephone_field :mobile, autofocus: true %>
						  </div>
							
						  <div class="field">
						    <%= f.label :email , class: 'required' %><br />
						    <%= f.email_field :email, autofocus: true %>
						  </div>
						  
						  <div class="field">
						    <%= f.label :password , class: 'required' %>
						    <% if @validatable %>
						    <em>(<%= @minimum_password_length %> characters minimum)</em>
						    <% end %><br />
						    <%= f.password_field :password, autocomplete: "off" %>
						  </div>
						
						  <div class="field">
						    <%= f.label :password_confirmation , class: 'required' %><br />
						    <%= f.password_field :password_confirmation, autocomplete: "off" %>
						  </div>
						  
						  <div class="field">
							<%= f.check_box :terms_of_service ,:acceptance =>{:accept => true}%>
							<%= f.label :terms_of_service,'Accept Temrs and Conditions' %></br>
						  </div>
						
						  <div class="actions">
						    <%= f.submit "Add Branch" %>
						  </div>
						  <%= link_to "Already have an account, Login", centre_sign_in_path %>
					</table>
				</div>
			<% end %>
		</div>		
	</div>	

app/views/centres/show.html.erb
<div class="row" style="color:#ff0000 ; background:#cccccc ; padding:50px; margin:0px;" %>
	<div class="col-md-1 offset2">
	</div>
	<h3>Branch Details</h3></br>
	<div class="col-md-4 offset2">
		<div class="row" style="color:#ff0000 ; background:#8899cc ; padding:20px; margin:0px;" %>
			<table>
				<h3>Profile</h3></br>
				<p>
				  <strong>Name:</strong>
				  <%= @centre.name %>
				</p>
				
				<p>
				  <strong>CentreType:</strong>
				  <%= @centre.centre_type.name %>
				</p>
				
				<p>
				  <strong>Company:</strong>
				  <%= @centre.company %>
				</p>
				
				<p>
				  <strong>Website:</strong>
				  <%= @centre.website %>
				</p>
				
				<p>
				  <strong>No of Employees:</strong>
				  <%= @centre.employee_count %>
				</p>
				
				<strong> Minimum_consultancy_fee </strong>
				<%= @centre.currency %>
				<%= @centre.minimum_consultancy_fee %><br>
				
				<p>
				  <strong>Closed Day:</strong>
				  <%= @centre.close_day %>
				</p>

				<% if @centre.open_time %>
				<p>
				  <strong>Clinic Timing:</strong>
				  <%= @centre.open_time.strftime("%H.%M") %> to 
				  <%= @centre.close_time.strftime("%H.%M") if @centre.close_time%>
				</p>
                <%end%>

				<%if @centre.lunch_start_time%>
				<p>
				  <strong>Lunch Timing:</strong>
				  <%= @centre.lunch_start_time.strftime("%H.%M") %> to
				  <%= @centre.lunch_end_time.strftime("%H.%M") if @centre.lunch_end_time%>
				</p>
				<%end%>
			</table>
		</div>
		
		<div class="row" style="color:#ff0000 ; background:#889955 ; padding:20px; margin:0px;" %>
			<table>
				<h3>Location</h3></br>
				<p>
				  <strong>Email:</strong>
				  <%= @centre.account.email %>
				</p>
				
				<p>
				  <strong>Secondary Email:</strong>
				  <%= @centre.secondary_email %>
				</p>
				
				<p>
				  <strong>Secondary Mobile:</strong>
				  <%= @centre.secondary_mobile %>
				</p>
				
				<p>
				  <strong>Address:</strong>
				  <%= @centre.address_line1 %>
				  <%= @centre.address_line2 %>
				  <%= @centre.address_line3 %>
				</p>
				
				<p>
				  <strong>Landmark</strong>
				  <%= @centre.landmark1 %>
				  <%= @centre.landmark2 %>
				  <%= @centre.landmark3 %>
				</p>
				
				<p>
				  <strong>Pincode:</strong>
				  <%= @centre.pincode %>
				</p>
				
				<p>
				  <strong>City:</strong>
				  <%= @centre.city %>
				</p>
				
				<p>
				  <strong>State:</strong>
				  <%= @centre.state %>
				</p>
				
				<p>
				  <strong>Country:</strong>
				  <%= @centre.country %>
				</p>
			</table>
		</div>
		
		<div class="row" style="color:#ff0000 ; background:#77ddff ; padding:20px; margin:0px;" %>
			<table >
				<h3>Login Details</h3></br>	
				<p>
				  <strong>Mobile:</strong>
				  <%= @centre.country_mobile_code %>-
				  <%= @centre.account.mobile%>
				</p>
				
				<p>
				  <strong>Email:</strong>
				  <%= @centre.account.email %>
				</p>
			</table>
		</div>
		
		<% if can? :edit, Centre %>
			<%= link_to "Edit", edit_centre_path(@centre) %>
		<% end %>
		<% if can? :destroy, Centre %>
    	  	<%= link_to 'Delete', centre_path(@centre), method: :delete,data: { confirm: 'Are you sure?'}%>
    	<% end %><br>
		<% if can? :show, Service %>
    	  	<%= link_to "Services", branch_services_path(@centre) %>
    	<% end %>
    	<% if can? :show, Facility %>
    	  	<%= link_to 'Facilities', branch_facilities_path(@centre)%>
    	<% end %><br>
	</div>
</div>